version: 2.1

orbs:
    php: circleci/php@1.1
    wp-svn: studiopress/wp-svn@0.1

jobs:
  test:
    docker:
      - image: cimg/php:7.3-node
    steps:
      - checkout
      - php/install-packages
      - run: composer phpcs

workflows:
  version: 2
  test-deploy:
    jobs:
      - test
      - approval-for-deploy-tested-up-to-bump:
          type: approval
          requires:
            - test
          filters:
            tags:
              ignore: /.*/
            branches:
              only: /^bump-tested-up-to.*/
      - wp-svn/deploy-tested-up-to-bump:
          context: genesis-svn
          requires:
            - approval-for-deploy-tested-up-to-bump
