version: 2.1

orbs:
    wp-svn: studiopress/wp-svn@0.1

jobs:
  test:
    docker:
      - image: circleci/php:7.3.3-stretch-node-browsers
    steps:
      - checkout
      - prepare-environment
      - run: composer phpcs

commands:
 prepare-environment:
   description: "Install dependencies."
   steps:
     - run: composer install

workflows:
  version: 2
  test-deploy:
    jobs:
      - test
      - approval-for-deploy-tested-up-to-bump:
          type: approval
          requires:
            - test
          filters:
            tags:
              ignore: /.*/
            branches:
              only: /^bump-tested-up-to.*/
      - wp-svn/deploy-tested-up-to-bump:
          context: genesis-svn
          requires:
            - approval-for-deploy-tested-up-to-bump
